[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'tomasr/molokai'
