[[plugins]]
on_ft = 'ruby'
repo = 'vim-ruby/vim-ruby'

[[plugins]]
on_ft = 'ruby'
repo = 'tpope/vim-rails'

[[plugins]]
on_ft = 'ruby'
repo = 'ngmy/vim-rubocop'

[[plugins]]
on_ft = 'javascript'
repo = 'pangloss/vim-javascript'

[[plugins]]
on_ft = 'md'
repo = 'plasticboy/vim-markdown'

[[plugins]]
on_ft = 'toml'
repo = 'cespare/vim-toml'
